version: "3.9"
services:
  django:
    container_name: "django_cont"
    build:
      context: .
    image: django_app
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    env_file:
      - ".env"
    networks:
      - notes-app-nw
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db:
    image: mysql
    container_name: "db_cont"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - notes-app-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  nginx:
    build:
      context: ./nginx
    container_name: "nginx_cont"
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - notes-app-nw
    restart: always

networks:
  notes-app-nw:
